name: Build Toolchain Workflow (Bookworm)

on:
  push:
    branches:
      - main
    paths:
      - 'source/**'
  pull_request:
    branches:
      - main
    paths:
      - 'source/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    strategy:
      matrix:
        architecture: [arm64, amd64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends binutils apt-utils dpkg-dev debian-archive-keyring equivs tar jq git devscripts build-essential lintian gdebi-core

      - name: Build libobjc2
        run: |
          ./cmd/main.sh --release bookworm --architecture ${{ matrix.architecture }} --no-sandbox -o libobjc2
        env:
          DEBIAN_FRONTEND: noninteractive
      
      - name: Build libdispatch
        run: |
          ./cmd/main.sh --release bookworm --architecture ${{ matrix.architecture }} --no-sandbox -o libdispatch
        env:
          DEBIAN_FRONTEND: noninteractive
      
      - name: Build gnustep-make
        run: |
          ./cmd/main.sh --release bookworm --architecture ${{ matrix.architecture }} --no-sandbox -o gnustep-make
        env:
          DEBIAN_FRONTEND: noninteractive
      
      - name: Build gnustep-base
        run: |
          ./cmd/main.sh --release bookworm --architecture ${{ matrix.architecture }} --no-sandbox -o gnustep-base
        env:
          DEBIAN_FRONTEND: noninteractive
      
      - name: Archive Packages
        run: |
          cd build/debian
          tar -cvzf packages-${{ matrix.architecture }}.tar.gz $(find . -type f \( -name "*.deb" -o -name "*.changes" -o -name "*.dsc" -o -name "*.ddeb" \))

      - name: Upload Packages
        uses: actions/upload-artifact@v3
        with:
          name: packages-bookworm-${{ matrix.architecture }}
          path: build/debian/packages-${{ matrix.architecture }}.tar.gz