name: Build Toolchain Workflow (Bookworm)

on:
  push:
    branches:
      - main
    paths:
      - 'source/**'
  pull_request:
    branches:
      - main
    paths:
      - 'source/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [arm64, amd64]
        include:
          - architecture: arm64
            image_suffix: bookworm-arm64
          - architecture: amd64
            image_suffix: bookworm-amd64
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends pbuilder binutils apt-utils tar jq git

      - name: Install Debian Archive Keyring
        run: |
          sudo apt-get install -y --no-install-recommends debian-archive-keyring gpg

      - name: Add the keyring to APT's trusted set
        run: |
          sudo cp /usr/share/keyrings/debian-archive-keyring.gpg /etc/apt/trusted.gpg.d/


      - name: Execute Build Script
        run: sudo ./cmd/main.sh --release bookworm --architecture ${{ matrix.architecture }}
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: List Resulting Packages
        run: |
          cd /var/cache/pbuilder/result
          find . -type f \( -name "*.deb" -o -name "*.changes" -o -name "*.dsc" \) -exec ls -l {} \;

      - name: Archive Packages
        uses: actions/upload-artifact@v3
        with:
          name: packages-${{ matrix.architecture }}
          path: /var/cache/pbuilder/result/*.{deb,changes,dsc}
