name: Build Toolchain Workflow (Bookworm)

on:
  push:
    branches:
      - main
    paths:
      - 'source/**'
  pull_request:
    branches:
      - main
    paths:
      - 'source/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends pbuilder binutils apt-utils dpkg-dev debian-archive-keyring equivs tar jq git devscripts build-essential lintian

      - name: Build libobjc2
        run: |
          sudo ./cmd/main.sh --release bookworm --architecture ${{ matrix.architecture }} --extract-only -o libobjc2
          cd build/debian/libobjc2

          sudo mk-build-deps --install --remove --tool='apt-get -y --no-install-recommends' debian/control
          sudo rm *.buildinfo *.changes

          sudo dpkg-source --build .
          sudo debuild -us -uc

          sudo dpkg -i ../libobjc2*.deb
          sudo apt-get remove --purge *-build-deps

          cd ../../..
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: List Resulting Packages
        run: |
          cd build/debian
          find . -type f \( -name "*.deb" -o -name "*.changes" -o -name "*.dsc" \) -exec ls -l {} \;

      - name: Archive Packages
        uses: actions/upload-artifact@v3
        with:
          name: packages-${{ matrix.architecture }}
          path: build/debian/*.{deb,changes,dsc}
